name: CI

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        node: ['14']
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    
    - name: Build the project
      run: |
        npm install
        npm run lint
        npm run build
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Apply eslint
          branch: master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
